### ISSUE TITLE
sqlalchemy upgrade needs flask sqlalchmeny upgrade too

### ISSUE THREAD

**Issue by breyten** [openstate/jodal#45]
Not upgrading resulted in this error:
```
api-jodal_1      | 2021-04-30 10:16:13,329.329.9117088317871:werkzeug:140127739356928:INFO:1:172.18.0.8 - - [30/Apr/2021 10:16:13] "GET /users/simple/me HTTP/1.0" 200 -
api-jodal_1      | 2021-04-30 10:16:13,334.334.5463275909424:app:140127730456320:ERROR:1:Exception on /columns [GET]
api-jodal_1      | Traceback (most recent call last):
api-jodal_1      |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
api-jodal_1      |     return self.registry[key]
api-jodal_1      | KeyError: <greenlet.greenlet object at 0x7f720679ca90 (otid=0x7f7206859580) current active started main>
api-jodal_1      | 
api-jodal_1      | During handling of the above exception, another exception occurred:
api-jodal_1      | 
api-jodal_1      | Traceback (most recent call last):
api-jodal_1      |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
api-jodal_1      |     rv = self.dispatch_request()
api-jodal_1      |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
api-jodal_1      |     return self.view_functions[rule.endpoint](**req.view_args)
api-jodal_1      |   File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 468, in wrapper
api-jodal_1      |     resp = resource(*args, **kwargs)
api-jodal_1      |   File "/usr/local/lib/python3.9/site-packages/flask/views.py", line 89, in view
api-jodal_1      |     return self.dispatch_request(*args, **kwargs)
api-jodal_1      |   File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
api-jodal_1      |     resp = meth(*args, **kwargs)
api-jodal_1      |   File "/opt/jodal/app/resources.py", line 24, in wrapper
api-jodal_1      |     return func(*args, **kwargs)
api-jodal_1      |   File "/opt/jodal/app/resources.py", line 36, in get
api-jodal_1      |     columns = Column.query.filter(Column.user_id==user_id)
api-jodal_1      |   File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 514, in __get__
api-jodal_1      |     return type.query_class(mapper, session=self.sa.session())
api-jodal_1      |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 129, in __call__
api-jodal_1      |     return self.registry()
api-jodal_1      |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
api-jodal_1      |     return self.registry.setdefault(key, self.createfunc())
api-jodal_1      |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4058, in __call__
api-jodal_1      |     return self.class_(**local_kw)
api-jodal_1      |   File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 138, in __init__
api-jodal_1      |     bind = options.pop('bind', None) or db.engine
api-jodal_1      |   File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 943, in engine
api-jodal_1      |     return self.get_engine()
api-jodal_1      |   File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 962, in get_engine
api-jodal_1      |     return connector.get_engine()
api-jodal_1      |   File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 555, in get_engine
api-jodal_1      |     options = self.get_options(sa_url, echo)
api-jodal_1      |   File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 570, in get_options
api-jodal_1      |     self._sa.apply_driver_hacks(self._app, sa_url, options)
api-jodal_1      |   File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 884, in apply_driver_hacks
api-jodal_1      |     sa_url.query.setdefault('charset', 'utf8')
api-jodal_1      | AttributeError: 'sqlalchemy.cimmutabledict.immutabledict' object has no attribute 'setdefault'
```

**Comment by breyten** [comment]
Related to https://github.com/pallets/flask-sqlalchemy/pull/919/files (fixed in dialog branch)
